# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bantersignup.ui'
#
# Created: Tue Sep 14 15:15:23 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_bantersignup(object):
    def setupUi(self, bantersignup):
        bantersignup.setObjectName("bantersignup")
        bantersignup.resize(645, 459)
        bantersignup.setStyleSheet("background-color: rgb(236, 218, 180);")
        self.centralwidget = QtGui.QWidget(bantersignup)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 30, 631, 41))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtGui.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(30, 10, 131, 21))
        self.label.setObjectName("label")
        self.firstname = QtGui.QLineEdit(self.frame)
        self.firstname.setGeometry(QtCore.QRect(290, 10, 251, 27))
        self.firstname.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.firstname.setObjectName("firstname")
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 90, 631, 41))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtGui.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(30, 10, 131, 21))
        self.label_2.setObjectName("label_2")
        self.lastname = QtGui.QLineEdit(self.frame_2)
        self.lastname.setGeometry(QtCore.QRect(290, 10, 251, 27))
        self.lastname.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lastname.setObjectName("lastname")
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(0, 150, 631, 41))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_3 = QtGui.QLabel(self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(30, 10, 131, 21))
        self.label_3.setObjectName("label_3")
        self.frame_8 = QtGui.QFrame(self.frame_3)
        self.frame_8.setGeometry(QtCore.QRect(0, 60, 631, 41))
        self.frame_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_4 = QtGui.QLabel(self.frame_8)
        self.label_4.setGeometry(QtCore.QRect(30, 10, 131, 21))
        self.label_4.setObjectName("label_4")
        self.uname = QtGui.QLineEdit(self.frame_3)
        self.uname.setGeometry(QtCore.QRect(290, 10, 251, 27))
        self.uname.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.uname.setEchoMode(QtGui.QLineEdit.Normal)
        self.uname.setObjectName("uname")
        self.frame_4 = QtGui.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(0, 210, 631, 41))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_5 = QtGui.QLabel(self.frame_4)
        self.label_5.setGeometry(QtCore.QRect(30, 10, 131, 21))
        self.label_5.setObjectName("label_5")
        self.frame_9 = QtGui.QFrame(self.frame_4)
        self.frame_9.setGeometry(QtCore.QRect(0, 60, 631, 41))
        self.frame_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_6 = QtGui.QLabel(self.frame_9)
        self.label_6.setGeometry(QtCore.QRect(30, 10, 131, 21))
        self.label_6.setObjectName("label_6")
        self.pswwd = QtGui.QLineEdit(self.frame_4)
        self.pswwd.setGeometry(QtCore.QRect(290, 10, 251, 27))
        self.pswwd.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pswwd.setEchoMode(QtGui.QLineEdit.Password)
        self.pswwd.setObjectName("pswwd")
        self.frame_5 = QtGui.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(0, 270, 631, 41))
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_7 = QtGui.QLabel(self.frame_5)
        self.label_7.setGeometry(QtCore.QRect(30, 10, 131, 21))
        self.label_7.setObjectName("label_7")
        self.frame_10 = QtGui.QFrame(self.frame_5)
        self.frame_10.setGeometry(QtCore.QRect(10, 60, 631, 41))
        self.frame_10.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_8 = QtGui.QLabel(self.frame_10)
        self.label_8.setGeometry(QtCore.QRect(30, 10, 131, 21))
        self.label_8.setObjectName("label_8")
        self.cpswwd = QtGui.QLineEdit(self.frame_5)
        self.cpswwd.setGeometry(QtCore.QRect(290, 10, 251, 27))
        self.cpswwd.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cpswwd.setEchoMode(QtGui.QLineEdit.Password)
        self.cpswwd.setObjectName("cpswwd")
        self.submitup = QtGui.QPushButton(self.centralwidget)
        self.submitup.setGeometry(QtCore.QRect(230, 380, 93, 27))
        self.submitup.setObjectName("submitup")
        bantersignup.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(bantersignup)
        self.statusbar.setObjectName("statusbar")
        bantersignup.setStatusBar(self.statusbar)

        self.retranslateUi(bantersignup)
        QtCore.QObject.connect(self.submitup, QtCore.SIGNAL("clicked(bool)"), bantersignup.update)
        QtCore.QObject.connect(self.cpswwd, QtCore.SIGNAL("returnPressed()"), self.submitup.update)
        QtCore.QObject.connect(self.submitup, QtCore.SIGNAL("clicked()"), bantersignup.close)
        QtCore.QMetaObject.connectSlotsByName(bantersignup)

    def retranslateUi(self, bantersignup):
        bantersignup.setWindowTitle(QtGui.QApplication.translate("bantersignup", "bantersignup", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("bantersignup", "first name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("bantersignup", "last name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("bantersignup", "user name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("bantersignup", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("bantersignup", "password", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("bantersignup", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("bantersignup", "confirm password", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("bantersignup", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.submitup.setText(QtGui.QApplication.translate("bantersignup", "submit", None, QtGui.QApplication.UnicodeUTF8))

