# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'banter2.ui'
#
# Created: Fri Sep 17 12:53:41 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Mbanter2(object):
    def setupUi(self, Mbanter2):
        Mbanter2.setObjectName("Mbanter2")
        Mbanter2.resize(263, 382)
        Mbanter2.setStyleSheet("background-color: qconicalgradient(cx:0.5, cy:0.5, angle:0, stop:0 rgba(35, 40, 3, 255), stop:0.16 rgba(136, 106, 22, 255), stop:0.225 rgba(166, 140, 41, 255), stop:0.285 rgba(204, 181, 74, 255), stop:0.345 rgba(235, 219, 102, 255), stop:0.415 rgba(245, 236, 112, 255), stop:0.52 rgba(209, 190, 76, 255), stop:0.57 rgba(187, 156, 51, 255), stop:0.635 rgba(168, 142, 42, 255), stop:0.695 rgba(202, 174, 68, 255), stop:0.75 rgba(218, 202, 86, 255), stop:0.815 rgba(208, 187, 73, 255), stop:0.88 rgba(187, 156, 51, 255), stop:0.935 rgba(137, 108, 26, 255), stop:1 rgba(35, 40, 3, 255));")
        self.centralwidget = QtGui.QWidget(Mbanter2)
        self.centralwidget.setObjectName("centralwidget")
        self.list = QtGui.QListWidget(self.centralwidget)
        self.list.setGeometry(QtCore.QRect(10, 50, 241, 281))
        self.list.setStyleSheet("background-color: rgb(236, 218, 180);\n"
"background-color: rgb(255, 255, 255);")
        self.list.setObjectName("list")
        QtGui.QListWidgetItem(self.list)
        QtGui.QListWidgetItem(self.list)
        QtGui.QListWidgetItem(self.list)
        QtGui.QListWidgetItem(self.list)
        QtGui.QListWidgetItem(self.list)
        QtGui.QListWidgetItem(self.list)
        QtGui.QListWidgetItem(self.list)
        QtGui.QListWidgetItem(self.list)
        QtGui.QListWidgetItem(self.list)
        QtGui.QListWidgetItem(self.list)
        QtGui.QListWidgetItem(self.list)
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 10, 301, 31))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.status = QtGui.QComboBox(self.frame)
        self.status.setGeometry(QtCore.QRect(0, 0, 111, 31))
        self.status.setStyleSheet("selection-background-color: rgb(255, 249, 201);\n"
"")
        self.status.setObjectName("status")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Desktop/nn/im-yahoo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.status.addItem(icon, "")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Desktop/nn/gdu-smart-healthy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.status.addItem(icon1, "")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../Desktop/nn/media-record.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.status.addItem(icon2, "")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../Desktop/nn/gdu-smart-threshold.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.status.addItem(icon3, "")
        self.invite = QtGui.QPushButton(self.frame)
        self.invite.setGeometry(QtCore.QRect(110, 0, 151, 31))
        self.invite.setObjectName("invite")
        self.signout = QtGui.QCommandLinkButton(self.centralwidget)
        self.signout.setGeometry(QtCore.QRect(160, 330, 91, 31))
        self.signout.setObjectName("signout")
        Mbanter2.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(Mbanter2)
        self.statusbar.setObjectName("statusbar")
        Mbanter2.setStatusBar(self.statusbar)
        self.actionVoice_chat = QtGui.QAction(Mbanter2)
        self.actionVoice_chat.setObjectName("actionVoice_chat")
        self.actionSing_out = QtGui.QAction(Mbanter2)
        self.actionSing_out.setObjectName("actionSing_out")
        self.actionClose = QtGui.QAction(Mbanter2)
        self.actionClose.setObjectName("actionClose")
        self.actionCut = QtGui.QAction(Mbanter2)
        self.actionCut.setObjectName("actionCut")
        self.actionCopy = QtGui.QAction(Mbanter2)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtGui.QAction(Mbanter2)
        self.actionPaste.setObjectName("actionPaste")

        self.retranslateUi(Mbanter2)
        QtCore.QObject.connect(self.invite, QtCore.SIGNAL("clicked()"), Mbanter2.update)
        QtCore.QMetaObject.connectSlotsByName(Mbanter2)

    def retranslateUi(self, Mbanter2):
        Mbanter2.setWindowTitle(QtGui.QApplication.translate("Mbanter2", "banter2", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.list.isSortingEnabled()
        self.list.setSortingEnabled(False)
        self.list.item(0).setText(QtGui.QApplication.translate("Mbanter2", "krish", None, QtGui.QApplication.UnicodeUTF8))
        self.list.item(1).setText(QtGui.QApplication.translate("Mbanter2", "vijay", None, QtGui.QApplication.UnicodeUTF8))
        self.list.item(2).setText(QtGui.QApplication.translate("Mbanter2", "ajay", None, QtGui.QApplication.UnicodeUTF8))
        self.list.item(3).setText(QtGui.QApplication.translate("Mbanter2", "manu", None, QtGui.QApplication.UnicodeUTF8))
        self.list.item(4).setText(QtGui.QApplication.translate("Mbanter2", "sangeetha", None, QtGui.QApplication.UnicodeUTF8))
        self.list.item(5).setText(QtGui.QApplication.translate("Mbanter2", "vidya", None, QtGui.QApplication.UnicodeUTF8))
        self.list.item(6).setText(QtGui.QApplication.translate("Mbanter2", "shyja", None, QtGui.QApplication.UnicodeUTF8))
        self.list.item(7).setText(QtGui.QApplication.translate("Mbanter2", "divya", None, QtGui.QApplication.UnicodeUTF8))
        self.list.item(8).setText(QtGui.QApplication.translate("Mbanter2", "dhanya", None, QtGui.QApplication.UnicodeUTF8))
        self.list.item(9).setText(QtGui.QApplication.translate("Mbanter2", "sunantha", None, QtGui.QApplication.UnicodeUTF8))
        self.list.item(10).setText(QtGui.QApplication.translate("Mbanter2", "maya", None, QtGui.QApplication.UnicodeUTF8))
        self.list.setSortingEnabled(__sortingEnabled)
        self.status.setItemText(0, QtGui.QApplication.translate("Mbanter2", "status", None, QtGui.QApplication.UnicodeUTF8))
        self.status.setItemText(1, QtGui.QApplication.translate("Mbanter2", "available", None, QtGui.QApplication.UnicodeUTF8))
        self.status.setItemText(2, QtGui.QApplication.translate("Mbanter2", "busy", None, QtGui.QApplication.UnicodeUTF8))
        self.status.setItemText(3, QtGui.QApplication.translate("Mbanter2", "idle", None, QtGui.QApplication.UnicodeUTF8))
        self.invite.setText(QtGui.QApplication.translate("Mbanter2", "invite a friend", None, QtGui.QApplication.UnicodeUTF8))
        self.signout.setText(QtGui.QApplication.translate("Mbanter2", "sign out", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVoice_chat.setText(QtGui.QApplication.translate("Mbanter2", "voice chat", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSing_out.setText(QtGui.QApplication.translate("Mbanter2", "sign out", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setText(QtGui.QApplication.translate("Mbanter2", "close", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCut.setText(QtGui.QApplication.translate("Mbanter2", "cut", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setText(QtGui.QApplication.translate("Mbanter2", "copy", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste.setText(QtGui.QApplication.translate("Mbanter2", "paste", None, QtGui.QApplication.UnicodeUTF8))

